const agentActionTypes = {
  AGENT_START_FETCH: "AGENT_START_FETCH",
  AGENT_SET_ERROR: "AGENT_SET_ERROR",
  AGENT_REMOVE_ERROR: "AGENT_REMOVE_ERROR",
  FETCH_AGENTS_REQUEST: "FETCH_AGENTS_REQUEST",
  FETCH_AGENTS_SUCCESS: "FETCH_AGENTS_SUCCESS",
  FETCH_AGENTS_FAILURE: "FETCH_AGENTS_FAILURE",
  REMOVE_FETCH_AGENTS: "REMOVE_FETCH_AGENTS",
  UPDATE_AGENT_STATUS: "UPDATE_AGENT_STATUS",
  UPDATE_AGENT_STATUS_ARRAY: "UPDATE_AGENT_STATUS_ARRAY",
  UPDATE_AGENT_IS_BUSY_STATUS: "UPDATE_AGENT_IS_BUSY_STATUS",
};

export default agentActionTypes;
