const loginActionTypes = {
  LOGIN_START_FETCH:"LOGIN_START_FETCH",
  LOGIN_SET_ERROR:"LOGIN_SET_ERROR",
  LOGIN_REMOVE_ERROR:"LOGIN_REMOVE_ERROR",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  REMOVE_POPUP: "REMOVE_POPUP",
  LOGOUT: "LOGOUT",
};

export default loginActionTypes;
